{"name": "Login with a non-existing user", "status": "passed", "description": "Test the login functionality with incorrect credentials.", "start": 1726410954670, "stop": 1726410954837, "uuid": "836d37cf-cb98-42fd-887d-9b6cb140c0ff", "historyId": "d77d0c3cc919ea143d253f7527478819", "testCaseId": "d77d0c3cc919ea143d253f7527478819", "fullName": "tests.test_login_user.TestLoginUser#test_non_existing_user_login", "labels": [{"name": "story", "value": "User Login Tests"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-OODMP73"}, {"name": "thread", "value": "9352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}